class PakistanCities {
  static const List<String> cities = [
    'Karachi',
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Hyderabad',
    'Gujranwala',
    'Peshawar',
    'Quetta',
    'Islamabad',
    'Bahawalpur',
    'Sargodha',
    'Sialkot',
    'Sukkur',
    'Larkana',
    'Sheikhupura',
    'Jhang',
    'Rahim Yar Khan',
    'Gujrat',
    'Mardan',
    'Kasur',
    'Mingora',
    'Dera Ghazi Khan',
    'Sahiwal',
    'Nawabshah',
    'Okara',
    'Mirpur Khas',
    'Chiniot',
    'Kamoke',
    'Sadiqabad',
    'Burewala',
    'Jacobabad',
    'Muzaffargarh',
    'Muridke',
    'Jhelum',
    'Shikarpur',
    'Hafizabad',
    'Kohat',
    'Khanpur',
    'Khuzdar',
    'Dadu',
    'Gojra',
    'Mandi Bahauddin',
    'Tando Allahyar',
    'Daska',
    'Pakpattan',
    'Bahawalnagar',
    'Tando Adam',
    'Khairpur',
    'Chishtian',
    'Abbottabad',
    'Jaranwala',
    'Ahmadpur East',
    'Vihari',
    'Kamalia',
    'Kot Addu',
    'Khushab',
    'Wazirabad',
    'Dera Ismail Khan',
    'Chakwal',
    'Swabi',
    'Lodhran',
    'Nowshera',
  ];
}
